### ISSUE TITLE
New Feature: Option to not throw an error if the tag is missing?

### ISSUE THREAD

**Issue by mukunku** [author/action-rollback#1]
I have a workflow where I'm removing the latest release and replacing it with a new one. But the first run of the workflow where no release exists experiences an error because there is no tag to delete. I haven't been able to find a way to determine, without failing the workflow, if a tag exists or not so maybe this option could be added to this action?

**Comment by mukunku** [comment]
I ended up creating my own action to first check if the tag exists or not: https://github.com/mukunku/tag-exists-action

**Comment by coreybutler** [comment]
I never saw the notice of this issue, so apologies for not responding earlier. If you're interested in merging your check into this action, I could see that being useful for people. Otherwise, I think a pre-check action is a great idea.
