### ISSUE TITLE
Deprecation warning regarding Node.js 12

### ISSUE THREAD

**Issue by FriedrichFroebel** [author/action-rollback#14]
**Issue:**

Using the action reports a deprecation warning:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: author/action-rollback.
```

**How To Reproduce:**

Include the action in a workflow file and run the corresponding workflow.

**Expected Behavior:**

No deprecated features are being used.

**Comment by coreybutler** [comment]
This is resolved in master, but has only had limited testing. For what it's worth, it's been working well in prod for us, we just haven't promoted it to a stable release yet. Use author/action-rollback@master.

**Comment by FriedrichFroebel** [comment]
Thanks for the hint (and sorry for the delay): I just tested it and it worked well in my case, too. I am going to leave this issue open while there is no release incorporating these changes as tagged releases are much nicer to use.

**Comment by FriedrichFroebel** [comment]
Is there any update on this? Apparently, GitHub now enforces Node16 now anyway: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by FriedrichFroebel** [comment]
By the way: This seems to fix the additional

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

warnings as well.

**Comment by FriedrichFroebel** [comment]
Is this action still maintained? In the meantime, Node16 will shortly be enforced already:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: author/action-rollback@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by coreybutler** [comment]
Yes, but it's not high on the priority list of everything I maintain. I tend to rely on PR's. That said, I've bumped the node version to 20 and released 1.0.4.

**Comment by FriedrichFroebel** [comment]
Thanks for the heads-up and the fix. I have to admit that my Node knowledge is non-existent, thus starting to arbitrarily create a PR here is rather unlikely.

**Comment by RadxaYuntian** [comment]
README.me is still recommending using `stable` as the action version. I suggest maintaining a `v1` tag which pointing to the latest 1.x.y release, and update the README.md to use this tag instead.
