### ISSUE TITLE
Input parameters always_delete_tag vs. delete_orphan_tag and date of next release?

### ISSUE THREAD

**Issue by jheilgeist** [author/action-rollback#2]
The example in the readme contains an input parameter "always_delete_tag", but the text describes an input parameter "delete_orphan_tag". The code on master uses "delete_orphan_tag".

When will this be merged into "stable" anyway?

Regards,
Janko

**Comment by coreybutler** [comment]
This was just a case of forgetting to update the README.

**Comment by coreybutler** [comment]
Updates have been merged into the stable branch.
